name: WakaTime Readme

on:
  schedule:
    - cron: "0 * * * *"   
  workflow_dispatch:      

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: "last_7_days"
          SECTION_NAME: "waka-week"

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: "all_time"
          SECTION_NAME: "waka-all"
